name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pachyuchepe/side-project
          stage: main
          yaml: >
            name: study-camp-socket-server

            app: node@18

            options:
              env:
                - name: PORT
                  value: ${{ secrets.PORT }}
                - name: CLIENT
                  value: ${{ secrets.CLIENT }}
                - name: MONGODB_ID
                  value: ${{ secrets.MONGODB_ID }}
                - name: MONGODB_PW
                  value: ${{ secrets.MONGODB_PW }}
                - name: MONGODB_NAME
                  value: ${{ secrets.MONGODB_NAME }}
              ports: "3500"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: node
